services:
  nginx-reverse-proxy:
    image: nginx:latest
    depends_on:
      - blog
      - minecraft
    ports:
      - 80:80
      - 443:443
      - "25565:25565"
    restart: always
    volumes:
      - ./nginx/:/etc/nginx/conf.d/:ro
      - certbot-www:/var/www/certbot/:ro
      - certbot-conf:/etc/nginx/ssl/:ro

  blog:
    image: lrotermund/blog:v1.13.0

  minecraft:
    image: itzg/minecraft-server:stable
    tty: true
    stdin_open: true
    environment:
      EULA: TRUE
      MEMORY: 8G
      TZ: CEST
      DIFFICULTY: normal
      MAX_PLAYERS: 4
      SERVER_NAME: CreeperComedyClub
      MOTD: "Booming with laughter, one creeper at a time!"
      WHITELIST: |
        Beeforce
        Kimikong
    volumes:
      - ./minecraft/data:/data

  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot-www:/var/www/certbot/:rw
      - certbot-conf:/etc/letsencrypt/:rw

volumes:
  certbot-www:
  certbot-conf:
